services:
  db:
    image: mysql:8.3.0
    container_name: ddm_mysql
    volumes:
      - /tmp/app/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"

  web:
    build:
      context: .
      dockerfile: docker/dev/django/Dockerfile
    container_name: ddm_django
    command: >
      sh -c "python -u manage.py runserver 0.0.0.0:8000"
    restart: on-failure
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
