# Generated by Django 5.0.3 on 2024-03-09 19:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        default="male",
                        max_length=10,
                    ),
                ),
                ("date_of_birth", models.DateTimeField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Employees",
                "db_table": "employees",
            },
        ),
        migrations.CreateModel(
            name="PersonalInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("citizen_identification_code", models.CharField(max_length=20)),
                ("personal_email", models.EmailField(max_length=254)),
                ("birthplace", models.CharField(max_length=255)),
                ("current_address", models.CharField(max_length=255)),
                ("permanent_address", models.CharField(max_length=255)),
                ("bank_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "bank_account_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("education", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "graduation_year",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2024),
                        ],
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        db_column="employee_code",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_information",
                        to="api.employee",
                        to_field="code",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Personal Informations",
                "db_table": "personal_informations",
            },
        ),
        migrations.CreateModel(
            name="WorkInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("probationary_start_date", models.DateField(null=True)),
                ("probationary_end_date", models.DateField(null=True)),
                ("official_start_date", models.DateField()),
                ("tax_code", models.CharField(max_length=255)),
                ("social_insurance_code", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("sse", "Server-side Engineer"),
                            ("cse", "Client-side Engineer"),
                            ("qa", "Quality assurance"),
                            ("pm", "Project manager"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("jr", "Junior"),
                            ("mid", "Middle"),
                            ("sr", "Senior"),
                            ("ex", "Expert"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        db_column="employee_code",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_information",
                        to="api.employee",
                        to_field="code",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Work Informations",
                "db_table": "work_informations",
            },
        ),
    ]
