# Generated by Django 5.0.3 on 2024-04-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_fileupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalinformation",
            name="phone_number",
            field=models.CharField(default="0", max_length=10),
            preserve_default=False,
        ),
    ]
